name: kube-score CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-action-job-win32:
    runs-on: windows-latest
    name: kube-score (Win32)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kube-score check
        uses: piraces/kube-score-ga@v0.1.0
        with:
          manifests-folders: './cassandra/*.yaml,./guestbook/*.yaml,./mysql-cinder-pd/*.yaml,./mysql-wordpress-pd/*.yaml'
